/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'Artur' at '11/3/13 7:08 PM' with Gradle 1.7
 *
 * @author Artur, @date 11/3/13 7:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
